<?php
/**
 * Created by PhpStorm.
 * User: XueSi <1592328848@qq.com>
 * Date: 2022-03-04
 * Time: 23:14
 */

namespace EasyApi\Db\Test;

use PHPUnit\Framework\TestCase;

class QueryTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testA()
    {
        $a = 1;
        $this->assertSame(1, $a);
    }
}