<?php
/**
 * Created by PhpStorm.
 * User: XueSi <1592328848@qq.com>
 * Date: 2022/3/6
 * Time: 1:03 下午
 */
declare(strict_types=1);

namespace EasyApi\Db\Test\Query;

use EasyApi\Db\Query;
use PHPUnit\Framework\TestCase;

class SelectTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function getQuery()
    {
        return new Query();
    }

    public function testWhereSelect()
    {
        // 查询一条数据
        $query = $this->getQuery();
        $sql = $query->table('easyswoole_user')->where(['a' => 1, 'b' => 2])->select();
        $this->assertEquals('SELECT * FROM `easyswoole_user` WHERE  `a` = 1  AND `b` = 2', $sql);

        $query = $this->getQuery();
        $sql = $query->table('user')->where('info$.email', 'mh@fdf')->find();
        $this->assertEquals("SELECT * FROM `user` WHERE  json_extract(info, '$.email') = 'mh@fdf' LIMIT 1", $sql);

        $sql = $this->getQuery()->table('easyswoole_user')->where('id', 1)->find();
        $this->assertEquals('SELECT * FROM `easyswoole_user` WHERE  `id` = 1 LIMIT 1', $sql);

        // 查询数据集使用
        $sql = $this->getQuery()->table('easyswoole_user')->where('status', 1)->select();
        $this->assertEquals('SELECT * FROM `easyswoole_user` WHERE  `status` = 1', $sql);
    }
}
